# Generated by Django 3.1 on 2021-04-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_create_initial_faculties'),
        ('institution', '0002_auto_20210427_1811'),
    ]

    operations = [
    ]
