# Generated by Django 3.1 on 2021-04-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_candidate_mugshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_ec_officer',
        ),
    ]
