# Generated by Django 3.1 on 2021-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_auto_20210428_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
